default_platform(:android)

platform :android do
  desc "Deploy to Play Store"
  lane :deploy do
    upload_to_play_store(
      track: 'production',
      aab: 'app/build/outputs/bundle/fullRelease/app-full-release.aab',
      skip_upload_metadata: false,
      skip_upload_images: false,
      skip_upload_screenshots: false,
      release_status: 'draft'
    )
  end
end
